<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/Feature_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from io import StringIO

data = """
Age,Gender,City,Salary,Experience,Married,Purchased
22,Male,Pune,25000,1,No,0
35,Female,Mumbai,50000,8,Yes,1
28,Male,Nashik,32000,3,No,0
45,Female,Pune,80000,15,Yes,1
31,Male,,45000,5,Yes,1
26,Female,Mumbai,,2,No,0
38,Male,Nashik,60000,,Yes,1
29,Female,Pune,40000,4,,0
50,Male,Mumbai,90000,20,Yes,1
24,Female,Nashik,28000,1,No,0
42,Male,Pune,75000,12,Yes,1
33,Female,,52000,7,No,1
27,Male,Mumbai,35000,3,No,0
48,Female,Nashik,85000,18,Yes,1
30,Male,Pune,,5,No,0
36,Female,Mumbai,58000,9,Yes,1
25,Male,Nashik,30000,,No,0
41,Female,Pune,72000,11,Yes,1
32,Male,Mumbai,47000,6,,1
29,Female,Nashik,39000,4,No,0
"""

df = pd.read_csv(StringIO(data))

df.head()

   Age  Gender    City   Salary  Experience Married  Purchased
0   22    Male    Pune  25000.0         1.0      No          0
1   35  Female  Mumbai  50000.0         8.0     Yes          1
2   28    Male  Nashik  32000.0         3.0      No          0
3   45  Female    Pune  80000.0        15.0     Yes          1
4   31    Male     NaN  45000.0         5.0     Yes          1

In [44]:
df.isnull()

,Age,Gender,Salary,Experience,Married,Purchased,City_Mumbai,City_Nashik,City_Pune,City_nan,City_Mumbai,City_Nashik,City_Pune,City_nan
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,True,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [45]:
df.fillna(df.mean(numeric_only=True))

,Age,Gender,Salary,Experience,Married,Purchased,City_Mumbai,City_Nashik,City_Pune,City_nan,City_Mumbai,City_Nashik,City_Pune,City_nan
0,22,1,25000.000000,1.000000,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,35,0,50000.000000,8.000000,1,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,28,1,32000.000000,3.000000,0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,45,0,80000.000000,15.000000,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,31,1,45000.000000,5.000000,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
5,26,0,52388.888889,2.000000,0,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,38,1,60000.000000,7.444444,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7,29,0,40000.000000,4.000000,2,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
8,50,1,90000.000000,20.000000,1,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,24,0,28000.000000,1.000000,0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
10,42,1,75000.000000,12.000000,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
11,33,0,52000.000000,7.000000,0,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
12,27,1,35000.000000,3.000000,0,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13,48,0,85000.000000,18.000000,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
14,30,1,52388.888889,5.000000,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
15,36,0,58000.000000,9.000000,1,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,25,1,30000.000000,7.444444,0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
17,41,0,72000.000000,11.000000,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
18,32,1,47000.000000,6.000000,2,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
19,29,0,39000.000000,4.000000,0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [46]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
LE = LabelEncoder()

In [49]:
df["Gender"] = LE.fit_transform(df["Gender"])

In [50]:
df["Married"] = LE.fit_transform(df["Married"])

In [51]:
df["Married"].head(3)

0    0
1    1
2    0
Name: Married, dtype: int64

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
encoder = OneHotEncoder()

In [26]:
encoded = encoder.fit_transform(df[["City"]])

In [33]:
encoded_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [36]:
df = pd.concat([df,encoded_df],axis=1)

In [ ]:
df.drop("City",axis=1,inplace=True)

In [55]:
df = df.loc[:, ~df.columns.duplicated()]

In [92]:
df["Experience"] = df["Experience"].fillna(df["Experience"].mean())

/tmp/ipykernel_2079/3718658292.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Experience"] = df["Experience"].fillna(df["Experience"].mean())

In [93]:
df.sample()

,Age,Gender,Salary,Experience,Married,Purchased,City_Mumbai,City_Nashik,City_Pune,City_nan,salary_per_exp
19,29,0,39000.0,4.0,0,0,0.0,1.0,0.0,0.0,9751.0

In [94]:
df["salary_per_exp"] = (df["Salary"]/ df["Experience"]+1)

/tmp/ipykernel_2079/1556106595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["salary_per_exp"] = (df["Salary"]/ df["Experience"]+1)

In [95]:
df.sample()

,Age,Gender,Salary,Experience,Married,Purchased,City_Mumbai,City_Nashik,City_Pune,City_nan,salary_per_exp
1,35,0,50000.0,8.0,1,1,1.0,0.0,0.0,0.0,6251.0

In [96]:
x = df.drop("Purchased",axis=1)

In [97]:
y = df["Purchased"]

In [98]:
from sklearn.model_selection import train_test_split

In [113]:
x_train , x_test , y_train ,y_test = train_test_split(x,y , train_size= 0.2,random_state=2)

In [100]:
from sklearn.linear_model import LogisticRegression

In [101]:
model = LogisticRegression()

In [102]:
model.fit(x_train,y_train)

LogisticRegression()

In [107]:
pred =model.predict(x_test)

In [108]:
from sklearn.metrics import accuracy_score

In [109]:
print(accuracy_score(pred, y_test))

0.875

In [110]:
from xgboost import XGBClassifier

In [111]:
model2 = XGBClassifier()

In [115]:
x_train , x_test , y_train ,y_test = train_test_split(x,y , train_size= 0.2,random_state=2)

In [117]:
model2.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [118]:
pred = model2.predict(x_test)

In [119]:
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [120]:
from sklearn.metrics import accuracy_score

In [121]:
print(accuracy_score(pred,y_test))

0.5

In [122]:
from sklearn.ensemble import RandomForestClassifier

In [123]:
model3 = RandomForestClassifier()

In [125]:
model3.fit(x_train,y_train)

RandomForestClassifier()

In [126]:
pred2 = model3.predict(x_test)

In [128]:
print(accuracy_score(pred2,y_test))

0.8125

In [129]:
print("On THIS dataset and THIS split,Logistic Regression performed best.")

On THIS dataset and THIS split,Logistic Regression performed best.