<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/fraud_dectection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("velvetcrystal/telecom-fraud-detection-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'telecom-fraud-detection-dataset' dataset.
Path to dataset files: /kaggle/input/telecom-fraud-detection-dataset

In [109]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics  import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [63]:
path

'/kaggle/input/telecom-fraud-detection-dataset'

In [64]:
os.listdir(path)

['telecom_fraud_detection_dataset.csv']

In [65]:
df = pd.read_csv(os.path.join(path,'telecom_fraud_detection_dataset.csv'))

In [66]:
df.head()

,call_id,caller_age_days,calls_per_day,call_duration_sec,avg_call_duration_sec,unique_receivers_24h,receiver_block_rate,spam_reports_count,country_code_risk_score,night_call_ratio,sequential_dialing_score,graph_degree,previous_fraud_associations,reputation_score,fraud_label
0,CALL0000001,735,7,449,372.5,9,12.60,4,26.08,15.18,5.19,59,0,88.06,0
1,CALL0000002,63,4,29,26.3,8,52.01,2,41.33,33.81,87.34,57,23,23.50,1
2,CALL0000003,473,24,61,72.8,6,5.24,1,3.12,25.49,32.84,48,0,74.23,0
3,CALL0000004,91,1270,27,37.1,156,36.88,72,50.15,59.64,98.80,351,15,41.23,1
4,CALL0000005,14,1344,69,64.8,135,72.19,3,42.58,85.61,51.92,575,28,17.94,1

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   call_id                      10000 non-null  object
 1   caller_age_days              10000 non-null  int64
 2   calls_per_day                10000 non-null  int64
 3   call_duration_sec            10000 non-null  int64
 4   avg_call_duration_sec        10000 non-null  float64
 5   unique_receivers_24h         10000 non-null  int64
 6   receiver_block_rate          10000 non-null  float64
 7   spam_reports_count           10000 non-null  int64
 8   country_code_risk_score      10000 non-null  float64
 9   night_call_ratio             10000 non-null  float64
 10  sequential_dialing_score     10000 non-null  float64
 11  graph_degree                 10000 non-null  int64
 12  previous_fraud_associations  10000 non-null  int64
 13  reputation_score             10000 non-null  float64
 14  fraud_label                  10000 non-null  int64
dtypes: float64(6), int64(8), object(1)
memory usage: 1.1+ MB

In [70]:
df = df.drop("call_id",axis=1)

In [71]:
df.describe()

,caller_age_days,calls_per_day,call_duration_sec,avg_call_duration_sec,unique_receivers_24h,receiver_block_rate,spam_reports_count,country_code_risk_score,night_call_ratio,sequential_dialing_score,graph_degree,previous_fraud_associations,reputation_score,fraud_label
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,773.626600,237.47800,213.367100,210.615840,50.356400,25.088838,18.030500,38.600140,31.241817,33.093151,163.497400,5.043000,63.496163,0.30000
std,728.549185,406.43526,163.899768,177.032595,77.776385,26.525415,32.166751,22.141158,22.258562,27.996123,149.269361,9.117415,26.654174,0.45828
min,0.000000,1.00000,1.000000,1.000000,0.000000,0.090000,0.000000,0.400000,0.180000,0.180000,1.000000,0.000000,0.360000,0.00000
25%,244.000000,6.00000,62.000000,55.800000,7.000000,5.960000,1.000000,20.590000,13.620000,11.310000,61.000000,0.000000,43.080000,0.00000
50%,618.000000,13.00000,198.000000,182.100000,9.000000,11.460000,2.000000,35.620000,24.810000,21.110000,108.000000,0.000000,72.730000,0.00000
75%,1088.000000,317.25000,314.000000,311.125000,73.000000,46.117500,4.000000,54.740000,45.662500,56.102500,220.000000,2.000000,84.882500,1.00000
max,3650.000000,1500.00000,1170.000000,1404.900000,524.000000,98.340000,111.000000,99.220000,98.220000,99.660000,1000.000000,41.000000,99.770000,1.00000

In [74]:
df.isnull().mean()*100

caller_age_days                0.0
calls_per_day                  0.0
call_duration_sec              0.0
avg_call_duration_sec          0.0
unique_receivers_24h           0.0
receiver_block_rate            0.0
spam_reports_count             0.0
country_code_risk_score        0.0
night_call_ratio               0.0
sequential_dialing_score       0.0
graph_degree                   0.0
previous_fraud_associations    0.0
reputation_score               0.0
fraud_label                    0.0
dtype: float64

In [75]:
df['fraud_label'].head()

0    0
1    1
2    0
3    1
4    1
Name: fraud_label, dtype: int64

In [76]:
si = SimpleImputer(strategy='mean')

In [78]:
x = df.drop('fraud_label',axis =1)

In [80]:
y = df['fraud_label']

In [81]:
x_train , x_test , y_train ,y_test = train_test_split(x,y,train_size=0.2,random_state=44)

In [82]:
x_train = si.fit_transform(x_train)

In [83]:
x_test = si.transform(x_test)

In [88]:
model = LogisticRegression()

In [89]:
model2 = RandomForestClassifier()

In [90]:
model.fit(x_train,y_train)

LogisticRegression()

In [91]:
Y_pred = model.predict(x_test)

In [52]:
print((Y_pred,y_test))

23.577033886072734

In [53]:
print(mean_absolute_percentage_error(Y_pred,y_test))

1.1450066047080312

In [54]:
Y_pred = model.predict(x_test)

In [55]:
df.shape

(284807, 31)

In [56]:
df.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
215696,140181.0,1.897237,-1.045324,-0.723901,0.482332,-0.682545,0.471377,-0.929156,0.182623,-0.236088,...,0.050125,0.537400,0.001142,0.307556,0.002641,-0.411663,0.047276,-0.025086,95.00,0
178821,123796.0,-0.089165,0.807445,-0.169992,-0.959017,1.048850,-0.200202,0.876518,-0.042459,-0.201535,...,-0.263317,-0.629031,-0.018891,-1.098890,-0.363124,0.176355,0.115003,0.069015,0.89,0
116146,74162.0,-0.548008,1.090936,1.250841,0.059566,0.483167,0.167768,0.545673,0.082322,-0.418184,...,-0.221859,-0.547656,-0.110065,-0.771866,-0.296708,0.238184,0.211957,0.167705,3.98,0
217497,140911.0,1.879869,-0.738779,0.074290,0.500984,-1.230859,-0.432876,-0.938795,0.124620,1.580257,...,0.060444,0.175369,0.301154,-0.029556,-0.653713,0.375509,-0.017136,-0.032395,49.90,0
64508,51173.0,-1.667069,-4.752934,0.176662,2.741291,-2.577133,1.085889,0.988047,-0.031683,1.031368,...,0.745247,-0.538085,-1.290726,0.665267,0.007989,-0.521276,-0.162199,0.275358,1414.74,0

In [ ]:
df.isnull().mean()*100

In [58]:
import matplotlib.pyplot as plt

In [60]:
import seaborn as sns

In [98]:
print(model.predict_proba(x_test))

[[1.00000000e+00 9.28389391e-14]
 [2.79754140e-07 9.99999720e-01]
 [4.44089210e-16 1.00000000e+00]
 ...
 [1.79769089e-10 1.00000000e+00]
 [9.99999996e-01 4.03639405e-09]
 [1.00000000e+00 7.42343223e-16]]

In [101]:
model2.fit(x_test,y_test)

RandomForestClassifier()

In [114]:
y_pred2 = model.predict(x_test)

In [102]:
print(model2.predict_proba(x_test))

[[1.   0.  ]
 [0.   1.  ]
 [0.   1.  ]
 ...
 [0.01 0.99]
 [1.   0.  ]
 [1.   0.  ]]

In [110]:
print(accuracy_score(Y_pred,y_test))

0.99875

In [116]:
print(accuracy_score(y_pred2,y_test))

0.99875