<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("brendan45774/test-file")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/brendan45774/test-file/6.archive...

100%|██████████| 11.2k/11.2k [00:00<00:00, 15.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/brendan45774/test-file/versions/6

In [64]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import  RandomForestClassifier
from sklearn.metrics import accuracy_score , confusion_matrix

In [6]:
os.listdir(path)

['tested.csv']

In [7]:
df = pd.read_csv(os.path.join(path,"tested.csv"))

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [9]:
df.shape

(418, 12)

In [19]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [12]:
df["Age"]= df["Age"].fillna(df["Age"].mean())

In [14]:
df["Fare"]= df["Fare"].fillna(df["Fare"].mean())

In [ ]:
df.isnull().sum()

In [18]:
df = df.drop("Cabin",axis=1)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Name      418 non-null    object
 3   Sex       418 non-null    object
 4   Age       418 non-null    float64
 5   Ticket    418 non-null    object
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    object
 8   family    418 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 29.5+ KB

In [23]:
df = df.drop("PassengerId",axis=1)

In [25]:
df["family"] = df["SibSp"]+df["Parch"]

In [ ]:
df = df.drop(columns =["SibSp","Parch",], axis =1)

In [30]:
df = df.drop(columns =["Name"], axis =1)

In [34]:
df.head(10)

,Survived,Pclass,Age,Ticket,Fare,family,Sex_male,Embarked_Q,Embarked_S
0,0,3,34.5,330911,7.8292,0,True,True,False
1,1,3,47.0,363272,7.0000,1,False,False,True
2,0,2,62.0,240276,9.6875,0,True,True,False
3,0,3,27.0,315154,8.6625,0,True,False,True
4,1,3,22.0,3101298,12.2875,2,False,False,True
5,0,3,14.0,7538,9.2250,0,True,False,True
6,1,3,30.0,330972,7.6292,0,False,True,False
7,0,2,26.0,248738,29.0000,2,True,False,True
8,1,3,18.0,2657,7.2292,0,False,False,False
9,0,3,21.0,A/4 48871,24.1500,2,True,False,True

In [33]:
df = pd.get_dummies(df,columns=["Sex","Embarked"],drop_first=True)

In [53]:
df = df.drop("Ticket",axis=1)

In [54]:
df.columns

Index(['Survived', 'Pclass', 'Age', 'Fare', 'family', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    418 non-null    int64
 1   Pclass      418 non-null    int64
 2   Age         418 non-null    float64
 3   Fare        418 non-null    float64
 4   family      418 non-null    int64
 5   Sex_male    418 non-null    bool
 6   Embarked_Q  418 non-null    bool
 7   Embarked_S  418 non-null    bool
dtypes: bool(3), float64(2), int64(3)
memory usage: 17.7 KB

In [56]:
x = df.drop("Survived",axis =1)
y = df["Survived"]

In [78]:
for i in [1, 10, 42, 100]:
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.2, random_state=i
    )

In [70]:
model = RandomForestClassifier()

In [79]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [72]:
pred = model.predict(x_test)

In [77]:
print(accuracy_score(pred,y_test))

1.0

In [76]:
print(confusion_matrix(pred, y_test))

[[52  0]
 [ 0 32]]

In [75]:
print(x.columns)

Index(['Pclass', 'Age', 'Fare', 'family', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [80]:
print("Got 100 percent accuracy its overfitting BTW   (:")

Got 100 percent accuracy its overfitting BTW   (: